name: Build Better Daily Log

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/wiiu-env/devkitppc:20260225

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y wget gpg

          wget -qO- https://apt.devkitpro.org/install-devkitpro-pacman \
            | bash

          dkp-pacman -Syu --noconfirm
          dkp-pacman -S --noconfirm --needed wut

      - name: Install WUPS
        run: |
          git clone https://github.com/wiiu-env/WiiUPluginSystem.git /tmp/wups
          cd /tmp/wups
          make install

      - name: Build
        run: make

      - name: Upload WPS
        uses: actions/upload-artifact@v4
        with:
          name: Better-Daily-Log
          path: "*.wps"
