name: Better Daily Log
version: 1.0.0
author: TheMysteriousStar
description: An Aroma plugin that improves the Daily Log user experience by adding TV information and Wii U Pro Controller and Wii Classic Controller input support.
license: GPL-3.0

repository: https://github.com/TheMysteriousStar/Better-Daily-Log

type: plugin
platform: wiiu
environment: aroma

files:
  - source: Better-Daily-Log.wps
    destination: wiiu/environments/aroma/plugins/Better-Daily-Log.wps
