name: Better Daily Log

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/wiiu-env/devkitppc:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install WUT
        run: |
          git clone --depth 1 https://github.com/devkitPro/wut.git /tmp/wut
          cd /tmp/wut
          make install

      - name: Install WUPS
        run: |
          git clone --depth 1 https://github.com/wiiu-env/WiiUPluginSystem.git /tmp/wups
          cd /tmp/wups
          make install

      - name: Build Better Daily Log
        run: |
          make

      - name: Upload WPS
        uses: actions/upload-artifact@v4
        with:
          name: Better-Daily-Log
          path: BetterDailyLog.wps
